HelpdeskSystem/Models/Profile.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HelpdeskSystem.Models
{
    public class Profile
    {
        public int Id { get; set; }

        [Required]
        [EmailAddress]
        [DisplayName("Adres email")]
        public string Username { get; set; }

        [Required]
        [DisplayName("Imię")]
        public string Firstname { get; set; }

        [Required]
        [DisplayName("Nazwisko")]
        public string Lastname { get; set; }

        [Required]
        [DisplayName("Rola w systemie")]
        public int RoleId { get; set; }

        [DisplayName("Data utworzenia")]
        public DateTime RegisteredDate { get; set; }


        public virtual Role Role { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
        public virtual ICollection<Ticket> OperatedTickets { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
}

HelpdeskSystem/Controllers/ProfilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using HelpdeskSystem.DataAccess;
using HelpdeskSystem.MailModels;
using HelpdeskSystem.Models;
using HelpdeskSystem.Utils;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security.DataProtection;
using RazorEngine;
using RazorEngine.Configuration;
using RazorEngine.Templating;

namespace HelpdeskSystem.Controllers
{

    public class ProfilesController : Controller
    {
        private HelpdeskContext db = new HelpdeskContext();

        // GET: Profiles
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View(db.Profiles.ToList());
        }

        // GET: Profiles/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profile profile = db.Profiles.Find(id);
            if (profile == null)
            {
                return HttpNotFound();
            }
            return View(profile);
        }

        // GET: Profiles/Create
        public ActionResult Create()
        {
            ViewBag.Roles = new List<SelectListItem>
            {
                new SelectListItem { Text = "Admin", Value = "Admin"},
                new SelectListItem { Text = "Obsługa", Value = "Staff" },
                new SelectListItem { Text = "Klient", Value = "Klient"}
            };
            return View();
        }

        // POST: Profiles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Username,Firstname,Lastname,RoleId")] Profile profile)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
                    var user = new ApplicationUser { Email = profile.Username, UserName = profile.Username };
                    var result = userManager.Create(user);
                    if (result.Succeeded)
                    {
                        userManager.AddToRole(user.Id, "Client");
                        profile.RegisteredDate = DateTime.Now;
                        db.Profiles.Add(profile);
                        db.SaveChanges();

                        string code = await userManager.GeneratePasswordResetTokenAsync(user.Id);
                        var callbackUrl = Url.Action("ResetPassword", "Account", new { userId = user.Id, code = code },
                            protocol: Request.Url.Scheme);
                        var model = new AccountCreatedViewModel
                        {
                            Firstname = profile.Firstname,
                            SiteUrl = Request.Url.GetLeftPart(UriPartial.Authority),
                            CallbackUrl = callbackUrl
                        };
                        var path = HttpContext.Server.MapPath("~/Views/Mail/SetPassword.cshtml");
                        var templateManager = new ResolvePathTemplateManager(new string[] { "~/Views/Mail/" });
                        var config = new TemplateServiceConfiguration
                        {
                            TemplateManager = templateManager
                        };
                        Engine.Razor = RazorEngineService.Create(config);
                        var html = Engine.Razor.RunCompile(path, null, model);
                        Mailing.SendMail(profile.Username, "Nowe konto w systemie", html);
                    }
                }
                catch (Exception ex)
                {
                    TempData["Error"] = "Wystapił błąd podczas dodawania nowego konta!";
                    TempData["ErrorDetails"] = ex.InnerException != null ? ex.InnerException.Message : ex.Message;
                }
                return RedirectToAction("Index");
            }
            return View(profile);
        }

        // GET: Profiles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profile profile = db.Profiles.Find(id);
            ViewBag.RoleId = new SelectList(db.Roles, "Id", "PolishName", profile.RoleId);
            if (profile == null)
            {
                return HttpNotFound();
            }
            return View(profile);
        }

        // POST: Profiles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Username,Firstname,Lastname,RegisteredDate,RoleId")] Profile profile)
        {
            if (ModelState.IsValid)
            {
                var userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
                var user = userManager.FindByName(profile.Username);
                var rolesForUser = userManager.GetRoles(user.Id);
                if (rolesForUser.Any())
                {
                    foreach (var item in rolesForUser.ToList())
                    {
                        var result = userManager.RemoveFromRole(user.Id, item);
                    }
                }
                userManager.AddToRole(user.Id, db.Roles.Find(profile.RoleId).Name);
                db.Entry(profile).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(profile);
        }

        // GET: Profiles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profile profile = db.Profiles.Find(id);
            if (profile == null)
            {
                return HttpNotFound();
            }
            return View(profile);
        }

        // POST: Profiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Profile profile = db.Profiles.Find(id);
            if (profile.Tickets.Any() || profile.Comments.Any())
            {
                throw new Exception("Usuwany profil posiada zależności! Nie można go usunąć tak łatwo!");
            }
            var userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            var user = userManager.FindByName(profile.Username);
            var logins = user.Logins;
            var rolesForUser = userManager.GetRoles(user.Id);
            foreach (var login in logins.ToList())
            {
                userManager.RemoveLogin(login.UserId, new UserLoginInfo(login.LoginProvider, login.ProviderKey));

            }

            if (rolesForUser.Any())
            {
                foreach (var item in rolesForUser.ToList())
                {
                    // item should be the name of the role
                    var result = userManager.RemoveFromRole(user.Id, item);
                }
            }

            userManager.Delete(user);
            db.Profiles.Remove(profile);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ContentResult GetFirstnameAndLastname(string email)
        {
            var profile = db.Profiles.FirstOrDefault(p => p.Username == email);
            return Content(profile.Firstname + " " + profile.Lastname);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HelpdeskSystem/Views/Profiles/Create.cshtml
@model HelpdeskSystem.Models.Profile

@{
    ViewBag.Title = "Tworzenie użytkownika";
}

<h2>Tworzenie użytkownika</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Użytkownik</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Firstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lastname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lastname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoleId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.RoleId, new SelectList( new string[] { "Admin", "Obsługa", "Klient"}), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RoleId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót do listy", "Index")
</div>

HelpdeskSystem/Views/Profiles/Delete.cshtml
@model HelpdeskSystem.Models.Profile

@{
    ViewBag.Title = "Usuwanie użytkownika";
}

<h2>Usuwanie użytkownika</h2>

<h3>Czy jesteś pewny, że chcesz usunąć podanego użytkownika?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Firstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lastname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lastname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RoleId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role.PolishName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegisteredDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegisteredDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-default" /> |
            @Html.ActionLink("Powrót do listy", "Index")
        </div>
    }
</div>

HelpdeskSystem/Views/Profiles/Details.cshtml
@model HelpdeskSystem.Models.Profile

@{
    ViewBag.Title = "Szczegóły użytkownika";
}

<h2>Szczegóły użytkownika</h2>

<div>
    <h4>Użytkownik</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Firstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lastname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lastname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RoleId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role.PolishName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegisteredDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegisteredDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edytuj", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Powrót do listy", "Index")
</p>

HelpdeskSystem/Views/Profiles/Edit.cshtml
@model HelpdeskSystem.Models.Profile

@{
    ViewBag.Title = "Edycja użytkownika";
}

<h2>Edycja użytkownika</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.RegisteredDate)

        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Firstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lastname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lastname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoleId,"Rola", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RoleId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RoleId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót do listy", "Index")
</div>

HelpdeskSystem/Views/Profiles/Index.cshtml
@model IEnumerable<HelpdeskSystem.Models.Profile>

@{
    ViewBag.Title = "Lista użytkowników";
}

<h2>Lista użytkowników</h2>

<p>
    <button type="button" class="btn btn-primary" onclick="location.href = '@Url.Action("Create", "Profiles")';return false;">Utwórz użytkownika</button>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Username)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Firstname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lastname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RegisteredDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoleId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Firstname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Lastname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RegisteredDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Role.PolishName)
        </td>
        <td>
            @Html.ActionLink("Edytuj", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Szczegóły", "Details", new { id = item.Id }) |
            @Html.ActionLink("Usuń", "Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>